name: bioemu
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - pyg
  - defaults 

dependencies:
  - python=3.12.0

  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.1 
  - pytorch::torchvision=0.19.0 

  - cuda-toolkit=12.1
  - cudnn 

  - cuda-version=12.1

  - pyg::pyg=2.6.1

  - conda-forge::mdtraj=1.9.9
  - conda-forge::openmm=8.2

  - gxx

  - pip:
    - "uv -i https://pypi.tuna.tsinghua.edu.cn/simple"

